configfile: "config.yaml"
RESULTS_DIR = config["results_dir"]

rule all:
    input:
        f"{RESULTS_DIR}/complete.fasta",
        f"{RESULTS_DIR}/non_cps.fasta",
        f"{RESULTS_DIR}/base_embeddings.npy",
        f"{RESULTS_DIR}/base_umap.pdf",
        f"{RESULTS_DIR}/contrastive_head.pth",
        f"{RESULTS_DIR}/contrastive_embeddings.npy",
        f"{RESULTS_DIR}/contrastive_umap.pdf",
        f"{RESULTS_DIR}/knn_report.txt",
        f"{RESULTS_DIR}/confusion_matrix_df.csv",
        f"{RESULTS_DIR}/kmer_sketch.npz",
        f"{RESULTS_DIR}/lda_rf_report.txt",
        f"{RESULTS_DIR}/lda_rf_confusion_matrix_df.csv",
        f"{RESULTS_DIR}/f1_distributions.pdf",
        f"{RESULTS_DIR}/distances.npz",
        f"{RESULTS_DIR}/distributions_params.json",

rule locus_cutter:
    input:
        fasta=config["fasta"],
        query=config["flank"]
    output:
        protected(f"{RESULTS_DIR}/complete.fasta"),
        protected(f"{RESULTS_DIR}/non_cps.fasta"),
    shell:
        """
        python scripts/locus_cutter.py \
            --fasta {input.fasta} \
            --query {input.query} \
            --output {output} \
            --cutoff 0.7 \
            --infiles /nfs/research/jlees/shorsfield/AtB_gene_predictions/S_pneumoniae_analysis/S_pneumoniae_HQ_abs_paths.txt \
            --outpref {RESULTS_DIR}/contigs \
            --query /hps/software/users/jlees/shorsfield/software/locus_cutter/testing/dexB_aliA_ATCC700669.fasta
        """

rule embed_transformer:
    input:
        fasta=config["fasta"]
    output:
        protected(f"{RESULTS_DIR}/base_embeddings.npy")
    params:
        model_name=config["model_name"],
        device=config["device"]
    shell:
        """
        python scripts/embed_transformer.py \
            --fasta {input.fasta} \
            --output {output} \
            --model_name {params.model_name} \
            --device {params.device}
        """

rule kmer_sketch:
    input:
        fasta=config["fasta"]
    output:
        protected(f"{RESULTS_DIR}/kmer_sketch.npz")
    params:
        k=config["sketch_k"],
        sketch_size=config["sketch_size"],
    shell:
        """
        python scripts/kmer_sketch.py \
            --fasta {input.fasta} \
            --output {output} \
            --k {params.k} \
            --sketch_size {params.sketch_size}
        """

rule visualize_umap:
    input:
        embeddings=f"{RESULTS_DIR}/base_embeddings.npy",
        labels=config["labels"]
    output:
        f"{RESULTS_DIR}/base_umap.pdf"
    shell:
        """
        python scripts/umap_visualize.py \
            --embeddings {input.embeddings} \
            --labels {input.labels} \
            --output {output} \
            --title "Base Transformer Embeddings UMAP"
        """

rule train_contrastive:
    input:
        embeddings=f"{RESULTS_DIR}/base_embeddings.npy",
        labels=config["labels"]
    output:
        f"{RESULTS_DIR}/contrastive_head.pth"
    params:
        device=config["device"],
        epochs=config["epochs"],
        batch_size=config["batch_size"],
        lr=config["lr"]
    shell:
        """
        python scripts/train_contrastive.py \
            --embeddings {input.embeddings} \
            --labels {input.labels} \
            --output {output} \
            --device {params.device} \
            --epochs {params.epochs} \
            --batch_size {params.batch_size} \
            --lr {params.lr} \
            --model-params '{config[model_params]}' \
            --labeled-only \
            --hierarchical-loss
        """

rule embed_contrastive:
    input:
        embeddings=f"{RESULTS_DIR}/base_embeddings.npy",
        head=f"{RESULTS_DIR}/contrastive_head.pth"
    output:
        f"{RESULTS_DIR}/contrastive_embeddings.npy"
    params:
        device=config["device"]
    shell:
        """
        python scripts/infer_contrastive.py \
            --embeddings {input.embeddings} \
            --head {input.head} \
            --output {output} \
            --device {params.device}
        """

rule knn_inference:
    input:
        embeddings=f"{RESULTS_DIR}/contrastive_embeddings.npy",
        labels=config["labels"]
    output:
        report=f"{RESULTS_DIR}/knn_report.txt",
        confusion_matrix=f"{RESULTS_DIR}/confusion_matrix_df.csv"
    shell:
        """
        python scripts/knn_inference.py \
            --embeddings {input.embeddings} \
            --labels {input.labels} \
            --knn_k {config[knn_k]} \
            --output-dir {RESULTS_DIR}
        """

rule visualize_contrastive_umap:
    input:
        embeddings=f"{RESULTS_DIR}/contrastive_embeddings.npy",
        labels=config["labels"]
    output:
        f"{RESULTS_DIR}/contrastive_umap.pdf"
    shell:
        """
        python scripts/umap_visualize.py \
            --embeddings {input.embeddings} \
            --labels {input.labels} \
            --output {output} \
            --title "Contrastive Embeddings UMAP"
        """

rule lda_analysis:
    input:
        embeddings=f"{RESULTS_DIR}/kmer_sketch.npz",
        labels=config["labels"]
    output:
        report=f"{RESULTS_DIR}/lda_rf_report.txt",
        confusion_matrix=f"{RESULTS_DIR}/lda_rf_confusion_matrix_df.csv"
    params:
        n_components=config["lda_components"]
    threads: 8
    shell:
        """
        python scripts/baseline_analysis.py \
            --embeddings {input.embeddings} \
            --labels {input.labels} \
            --n_components {params.n_components} \
            --test_size 0.2 \
            --output-dir {RESULTS_DIR}
        """

rule stats_summary:
    """
    Generate a lineplot of class-wise F1 distributions for
    each confusion matrix to compare analysis methods.
    """
    input:
        cm_files=[
            f"{RESULTS_DIR}/lda_rf_confusion_matrix_df.csv",
            f"{RESULTS_DIR}/confusion_matrix_df.csv"
        ]
    params:
        legend_labels=["LDA", "Contrastive"],
    output:
        f"{RESULTS_DIR}/f1_distributions.pdf"
    shell:
        """
        python scripts/statistical_summary.py \
            --confusion_matrices {input.cm_files} \
            --legend {params.legend_labels} \
            --output {output}
        """

rule calc_distances:
    input:
        embeddings=f"{RESULTS_DIR}/contrastive_embeddings.npy",
        labels=config["labels"]
    output:
        f"{RESULTS_DIR}/distances.npz"
    shell:
        """
        python scripts/calc_distances.py \
            --embeddings {input.embeddings} \
            --labels {input.labels} \
            --output {output}
        """

rule novel_detection:
    input:
        query=config["query_path"],
        embeddings=f"{RESULTS_DIR}/contrastive_embeddings.npy",
        labels=config["labels"],
        distances=f"{RESULTS_DIR}/distances.npz"
    params:
        thresholds=config["novelty_thresholds"]
    output:
        f"{RESULTS_DIR}/novel_detection_report.txt",
        f"{RESULTS_DIR}/distributions_params.json",
    shell:
        """
        python scripts/novel_detection.py \
            --query {params.query} \
            --embeddings {input.embeddings} \
            --labels {input.labels} \
            --distances {input.distances} \
            --thresholds {params.thresholds} \
            --output-dir {RESULTS_DIR}
        """